Update dependencies; tonic 0.10.2, prost 0.12.3
flemosr/envoy-types pull request #1
Opened 2024-01-25 01:15 UTC by davidrjonas

| Package                 | From    | To      | Compare   |
|-------------------------|---------|---------|-----------|
| [async-stream][01]      | NEW     | 0.3.5   |           |
| [async-stream-impl][02] | NEW     | 0.3.5   |           |
| lazy_static             | 1.4.0   | REMOVED |           |
| [libc][03]              | 0.2.147 | 0.2.152 | [...][04] |
| [mio][05]               | 0.8.8   | 0.8.10  | [...][06] |
| [pin-project-lite][07]  | 0.2.10  | 0.2.13  | [...][08] |
| [prettyplease][09]      | 0.1.25  | 0.2.15  | [...][0A] |
| [prost][0B]             | 0.11.9  | 0.12.3  | [...][0C] |
| [prost-build][0D]       | 0.11.9  | 0.12.3  | [...][0E] |
| [prost-derive][0F]      | 0.11.9  | 0.12.3  | [...][10] |
| [prost-types][11]       | 0.11.9  | 0.12.3  | [...][12] |
| [socket2][13]           | NEW     | 0.5.5   |           |
| [syn][14]               | 2.0.27  | 2.0.32  | [...][15] |
| [tokio][16]             | 1.29.1  | 1.35.1  | [...][17] |
| tokio-macros            | 2.1.0   | REMOVED |           |
| [tonic][18]             | 0.9.2   | 0.10.2  | [...][19] |
| [tonic-build][1A]       | 0.9.2   | 0.10.2  | [...][1B] |

[01]: https://crates.io/crates/async-stream
[02]: https://crates.io/crates/async-stream-impl
[03]: https://crates.io/crates/libc
[04]: https://github.com/rust-lang/libc/compare/0%2E2%2E147...0%2E2%2E152
[05]: https://crates.io/crates/mio
[06]: https://github.com/tokio-rs/mio/compare/0%2E8%2E8...0%2E8%2E10
[07]: https://crates.io/crates/pin-project-lite
[08]: https://github.com/taiki-e/pin-project-lite/compare/0%2E2%2E10...0%2E2%2E13
[09]: https://crates.io/crates/prettyplease
[0A]: https://github.com/dtolnay/prettyplease/compare/0%2E1%2E25...0%2E2%2E15
[0B]: https://crates.io/crates/prost
[0C]: https://github.com/tokio-rs/prost/compare/0%2E11%2E9...0%2E12%2E3
[0D]: https://crates.io/crates/prost-build
[0E]: https://github.com/tokio-rs/prost/compare/0%2E11%2E9...0%2E12%2E3
[0F]: https://crates.io/crates/prost-derive
[10]: https://github.com/tokio-rs/prost/compare/0%2E11%2E9...0%2E12%2E3
[11]: https://crates.io/crates/prost-types
[12]: https://github.com/tokio-rs/prost/compare/0%2E11%2E9...0%2E12%2E3
[13]: https://crates.io/crates/socket2
[14]: https://crates.io/crates/syn
[15]: https://github.com/dtolnay/syn/compare/2%2E0%2E27...2%2E0%2E32
[16]: https://crates.io/crates/tokio
[17]: https://github.com/tokio-rs/tokio/compare/1%2E29%2E1...1%2E35%2E1
[18]: https://crates.io/crates/tonic
[19]: https://github.com/hyperium/tonic/compare/0%2E9%2E2...0%2E10%2E2
[1A]: https://crates.io/crates/tonic-build
[1B]: https://github.com/hyperium/tonic/compare/0%2E9%2E2...0%2E10%2E2

2024-01-25 01:16 UTC, davidrjonas commented
Thanks for creating this crate. You've saved me a ton of time!

2024-01-30 13:31 UTC, flemosr requested changes
Thanks @davidrjonas! We just need a small adjustment and then we can merge.

2024-01-30 13:31 UTC, flemosr commented on examples/Cargo.toml
> +tokio = { version = "1.35.1", features = ["rt-multi-thread"] }
```suggestion
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
```
We need this feature to run our examples.

2024-01-31 11:45 UTC, flemosr approved these changes

2024-01-31 11:58 UTC, merged